tracelogger={
   priority=20
}

port = 9500
sslport = 9543

oauth_portal="http://localhost:" .. tostring(port) .. "/sso/"

openid={
   tenant="d1b3ad34",
   client_id="9db199ec",
   client_secret="D2T8Q"
}

-- Used by .preload for setting SMQ keepalive
keepidle = 60
keepintv = 2

apps={
   {path="apps/mock_sso",name="sso"},
   {path="apps/login",name="login"},
   {path="apps/esp32_simulator",name="device_sim"},
   {path="apps/esp32",name="device"},
}
